BASE_URL = "https://stellarburgers.nomoreparties.site/api"
REGISTER = f"{BASE_URL}/auth/register"
LOGIN = f"{BASE_URL}/auth/login"
USER_PROFILE = f"{BASE_URL}/auth/user"
ORDERS = f"{BASE_URL}/orders"